### ISSUE TITLE
为什么下载下来，到 IDEA 运行还是会出错

### ISSUE THREAD

**Issue by newcaoguo** [chenfromsz/spring-boot-db#7]
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.ValidationException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499) ~[na:na]
	... 51 common frames omitted

Process finished with exit code 1
贴出来错误提示

**Comment by chenfromsz** [comment]
用jdk1.8吗？刷新一下maven，看是不是一些依赖包没有加载完整。

**Comment by newcaoguo** [comment]
我用的 jdk 10 也不行

**Comment by newcaoguo** [comment]
是项目覆盖的时候出错了，我导入的时候命令为另外的就可以了
